version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
